# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.18.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.18.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/zhangpei/mine/coroutinedh

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/zhangpei/mine/coroutinedh

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.18.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.18.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zhangpei/mine/coroutinedh/CMakeFiles /Users/zhangpei/mine/coroutinedh//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zhangpei/mine/coroutinedh/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named coroutine

# Build rule for target.
coroutine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 coroutine
.PHONY : coroutine

# fast build rule for target.
coroutine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coroutine.dir/build.make CMakeFiles/coroutine.dir/build
.PHONY : coroutine/fast

#=============================================================================
# Target rules for targets named test_swap

# Build rule for target.
test_swap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_swap
.PHONY : test_swap

# fast build rule for target.
test_swap/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_swap.dir/build.make CMakeFiles/test_swap.dir/build
.PHONY : test_swap/fast

#=============================================================================
# Target rules for targets named test_ctx

# Build rule for target.
test_ctx: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ctx
.PHONY : test_ctx

# fast build rule for target.
test_ctx/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ctx.dir/build.make CMakeFiles/test_ctx.dir/build
.PHONY : test_ctx/fast

contextu.o: contextu.c.o

.PHONY : contextu.o

# target to build an object file
contextu.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coroutine.dir/build.make CMakeFiles/coroutine.dir/contextu.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_swap.dir/build.make CMakeFiles/test_swap.dir/contextu.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ctx.dir/build.make CMakeFiles/test_ctx.dir/contextu.c.o
.PHONY : contextu.c.o

contextu.i: contextu.c.i

.PHONY : contextu.i

# target to preprocess a source file
contextu.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coroutine.dir/build.make CMakeFiles/coroutine.dir/contextu.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_swap.dir/build.make CMakeFiles/test_swap.dir/contextu.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ctx.dir/build.make CMakeFiles/test_ctx.dir/contextu.c.i
.PHONY : contextu.c.i

contextu.s: contextu.c.s

.PHONY : contextu.s

# target to generate assembly for a file
contextu.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coroutine.dir/build.make CMakeFiles/coroutine.dir/contextu.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_swap.dir/build.make CMakeFiles/test_swap.dir/contextu.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ctx.dir/build.make CMakeFiles/test_ctx.dir/contextu.c.s
.PHONY : contextu.c.s

coroutine.o: coroutine.c.o

.PHONY : coroutine.o

# target to build an object file
coroutine.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coroutine.dir/build.make CMakeFiles/coroutine.dir/coroutine.c.o
.PHONY : coroutine.c.o

coroutine.i: coroutine.c.i

.PHONY : coroutine.i

# target to preprocess a source file
coroutine.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coroutine.dir/build.make CMakeFiles/coroutine.dir/coroutine.c.i
.PHONY : coroutine.c.i

coroutine.s: coroutine.c.s

.PHONY : coroutine.s

# target to generate assembly for a file
coroutine.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coroutine.dir/build.make CMakeFiles/coroutine.dir/coroutine.c.s
.PHONY : coroutine.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coroutine.dir/build.make CMakeFiles/coroutine.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coroutine.dir/build.make CMakeFiles/coroutine.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/coroutine.dir/build.make CMakeFiles/coroutine.dir/main.c.s
.PHONY : main.c.s

test_ctx.o: test_ctx.cpp.o

.PHONY : test_ctx.o

# target to build an object file
test_ctx.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ctx.dir/build.make CMakeFiles/test_ctx.dir/test_ctx.cpp.o
.PHONY : test_ctx.cpp.o

test_ctx.i: test_ctx.cpp.i

.PHONY : test_ctx.i

# target to preprocess a source file
test_ctx.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ctx.dir/build.make CMakeFiles/test_ctx.dir/test_ctx.cpp.i
.PHONY : test_ctx.cpp.i

test_ctx.s: test_ctx.cpp.s

.PHONY : test_ctx.s

# target to generate assembly for a file
test_ctx.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_ctx.dir/build.make CMakeFiles/test_ctx.dir/test_ctx.cpp.s
.PHONY : test_ctx.cpp.s

test_swap.o: test_swap.cpp.o

.PHONY : test_swap.o

# target to build an object file
test_swap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_swap.dir/build.make CMakeFiles/test_swap.dir/test_swap.cpp.o
.PHONY : test_swap.cpp.o

test_swap.i: test_swap.cpp.i

.PHONY : test_swap.i

# target to preprocess a source file
test_swap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_swap.dir/build.make CMakeFiles/test_swap.dir/test_swap.cpp.i
.PHONY : test_swap.cpp.i

test_swap.s: test_swap.cpp.s

.PHONY : test_swap.s

# target to generate assembly for a file
test_swap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_swap.dir/build.make CMakeFiles/test_swap.dir/test_swap.cpp.s
.PHONY : test_swap.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... coroutine"
	@echo "... test_ctx"
	@echo "... test_swap"
	@echo "... contextu.o"
	@echo "... contextu.i"
	@echo "... contextu.s"
	@echo "... coroutine.o"
	@echo "... coroutine.i"
	@echo "... coroutine.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... test_ctx.o"
	@echo "... test_ctx.i"
	@echo "... test_ctx.s"
	@echo "... test_swap.o"
	@echo "... test_swap.i"
	@echo "... test_swap.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

